apiVersion: v1
kind: Service
metadata:
  name: hotel-reservation-app
  namespace: sc-mvp-test
  labels:
    app: hotel-reservation-app
spec:
  type: ClusterIP
  selector:
    app: hotel-reservation-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
